repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-json
    - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    - id: codespell
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
    - id: mypy
