repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-json
    - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
    - id: cppcheck
    - id: cpplint
      args:
        - --filter=-legal/copyright,-build/namespaces,-runtime/string,-whitespace/newline
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    - id: codespell
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    - id: mypy
